// <auto-generated />
namespace AdminPanelLesson.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ADDreqiredFullNameforVisitor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDreqiredFullNameforVisitor));
        
        string IMigrationMetadata.Id
        {
            get { return "201812220611068_ADD reqired FullName for Visitor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
